import React from "react";

export default function Page() {
  return (
    <div>
      <div className="h-full w-9/12 bg-slate-400 mx-auto">
        <div className="h-60 w-full grid gap-2 p-2 grid-cols-2 grid-rows-2">
          <div className="col-span-2 row-span-2 rounded-xl bg-white overflow-auto">
            <table className="table-auto w-full">
              <thead className="sticky top-0 bg-gray-700 text-white">
                <tr>
                  <th className="text-red-800 py-2">Date</th>
                  <th className="text-red-800">Chemical Name</th>
                  <th className="text-red-800">Supplier Name</th>
                  <th className="text-red-800">Supplier Name</th>
                  <th className="text-red-800">Supplier Name</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
                <tr>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                  <td>sdadsa</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
